services:
  bombsquad:
    container_name: bombsquad_server
    image: bombsquad_ballistica_server
    build: .
    pull_policy: never
    ports:
      - "43210:43210/udp"
    volumes:
      - /etc/machine-id:/etc/machine-id:ro
      - ./config.json:/app/config.json
    logging:
      options:
        max-size: "1g"
    networks:
      - nginx_proxy_shared

networks:
  nginx_proxy_shared:
    external: true
